export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const UPADTE_QUANTITY_IN_CART = 'UPADTE_QUANTITY_IN_CART';