export const MSG_ADD_TO_CART_SUCCESS = 'Mua hàng thành công !'
export const MSG_UPDATE_TO_CART_SUCCESS = 'Cập nhật thành công !'
export const MSG_DELETE_PRODUCT_IN_CART_SUCCESS = 'Xóa sản phẩm thành công !'
export const MSG_CART_EMTY = 'Chưa có sản phẩm nào !'
export const MSG_WELCOME = 'Chào mừng đến với Shopping online !'
